### ISSUE TITLE
Removable form elements

### ISSUE THREAD

**Issue by uguryuruk** [anburocky3/bootstrap5-snippets#15]
I have tested all the form elements (i.e. form- snippets). These items can be removed:

- [ ] custom-checkbox (not working)
- [ ] custom-file (not working)
- [ ] form-input-text (default form input is enough)
- [ ] radio-custom (not working)

all select items can be merged into one.
all multi-select items can be merged into one. (I can send a PR about selects)

**Comment by anburocky3** [comment]
You have already removed these templates in https://github.com/anburocky3/bootstrap5-snippets/pull/13 right?

If that so, in generated templates, the snippets which you said not working, should not be present.

**Comment by uguryuruk** [comment]
Yeah, that's true I have removed them but somehow they appear in the live version:
![image](https://user-images.githubusercontent.com/67945825/172055738-07d467c5-d941-49f5-a26b-74c80d12f17c.png)

**Comment by anburocky3** [comment]
Hopefully, it will be resolved in the next release.

**Comment by uguryuruk** [comment]
Allright, I have a question. I would like to write descriptions for the snippets. Is there anyway other than updating snippets.json?

**Comment by anburocky3** [comment]
> Allright, I have a question. I would like to write descriptions for the snippets. Is there anyway other than updating snippets.json?

We have around 173 snippets, Can we do that for all? 

Currently the automatic generation does it (basically, it pulls the path and gives as description name). But after the release of Snippet Generator, i'll add this functionality and at that time, we can do that i think so? What do you think?

**Comment by uguryuruk** [comment]
If you show me the way, I can do it for all. No problem :) 

I wrote some comments in some templates, however I would like to write detailed (maybe 1-2 sentence) descriptions for the snippets. That would be great for beginners.

**Comment by anburocky3** [comment]
> Allright, I have a question. I would like to write descriptions for the snippets. Is there anyway other than updating snippets.json?

Regarding this, we can track in different dedicated issue: https://github.com/anburocky3/bootstrap5-snippets/issues/16

**Comment by anburocky3** [comment]
@uguryuruk This can be closed right? I hope, you have fixed it in #18 (v0.4.0 release)

**Comment by anburocky3** [comment]
@uguryuruk Can we close this issue?

**Comment by uguryuruk** [comment]
Yes of course.
