### ISSUE TITLE
"bs5-card-grid" shortcut gives a template with the deprecated "xs" breakpoint

### ISSUE THREAD

**Issue by StefanoMiC** [anburocky3/bootstrap5-snippets#17]
![image](https://user-images.githubusercontent.com/26657904/177193289-45acba9f-165c-4db4-ac66-3b09300e673c.png)

In modern bootstrap the breakpoint "xs" is deprecated since it is the default 

![image](https://user-images.githubusercontent.com/26657904/177193418-4ec374de-dc5d-4acd-bb29-5ec7a2de11ce.png)

![image](https://user-images.githubusercontent.com/26657904/177193401-084f74cf-d89a-4288-b67c-d7a250799ba2.png)

**Comment by anburocky3** [comment]
Thank you for reporting. We will add it to our backlog. Will fix those in our next release.

**Comment by uguryuruk** [comment]
@anburocky3  @StefanoMiC I have fixed this in #14.

**Comment by anburocky3** [comment]
Fixed it in #18 Thank you for reporting.

**Comment by StefanoMiC** [comment]
Thank you @anburocky3 !
