### ISSUE TITLE
TAB spacing is not standar

### ISSUE THREAD

**Issue by tohizma** [anburocky3/bootstrap5-snippets#21]
Would you please use standard TAB spacing using 4 spaces instead 2 or 3 for all snippets?

It is iritating to always repair generated snippet identation

thank you

**Comment by anburocky3** [comment]
We have made all templates, now to follow the same tab spacing (4 spaces).

**Please check:**
Can you please check in the latest https://github.com/anburocky3/bootstrap5-snippets/releases/tag/v0.4.4
