### ISSUE TITLE
In Media snippet most of the type styles are same

### ISSUE THREAD

**Issue by yogesh7401** [anburocky3/bootstrap5-snippets#4]
## In Media snippet most of types are same 
![media](https://user-images.githubusercontent.com/58160728/125465848-2647605a-621f-44da-8abb-7ca8caa0c4a8.PNG)

#### And There is no bootstrap className like

- align-self-bottom

#### Instead of this use 

- align-self-end

**Comment by anburocky3** [comment]
Working in v0.1.1
