### ISSUE TITLE
doesnt work inside php.. 

### ISSUE THREAD

**Issue by sagive** [anburocky3/bootstrap5-snippets#6]
FYI: 
i think that in half the cases, bootstrap is being used inside Wordpress / druppel etc..
however you plugin isn't activated inside PHP...

**Comment by anburocky3** [comment]
It works! Check the below screenshot. can you create a new PHP file and check it again?

![image](https://user-images.githubusercontent.com/15264938/130272343-f349c233-8f6c-408e-b0c8-f6078e3c0dd3.png)

**VSCode Version:** 1.59.0

**Comment by anburocky3** [comment]
@sagive Can you check again?

**Comment by sagive** [comment]
sure, will try asap and update

**Comment by sagive** [comment]
Works! thank you very much 👍👍
